name: Process Department Content

on:
  issues:
    types: [opened, edited]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  generate-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 需要完整历史记录来创建新分支

      - name: 安装依赖
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.35.1/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          pip install pyyaml          # 安装 Python YAML 库

      - name: 提取模板字段
        id: extract-fields
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          cat > extract.py << 'EOF'
          import os, sys

          def extract_section(body, section_name):
              """提取指定部分的内容"""
              if not body:
                  return None
                  
              marker = "### " + section_name
              if marker not in body:
                  return None
                  
              # 找到部分的开始
              start = body.find(marker) + len(marker)
              
              # 找到下一个部分的开始（如果有）
              next_section = body.find("###", start)
              if next_section != -1:
                  section_content = body[start:next_section]
              else:
                  section_content = body[start:]
                  
              return section_content.strip()
              
          def extract_content(body):
              """提取主要内容（代码块）"""
              section = extract_section(body, "主要内容")
              if not section:
                  return None
                  
              # 查找代码块
              start = section.find("```")
              if start == -1:
                  return None
                  
              # 跳过```行
              start = section.find("\n", start) + 1
              if start == 0:  # 没有找到换行符
                  return None
                  
              # 找到结束的```
              end = section.find("```", start)
              if end == -1:
                  return None
                  
              return section[start:end].strip()

          # 主程序
          body = os.environ.get("ISSUE_BODY", "")
          print("Issue内容:", body[:100] + "..." if len(body) > 100 else body)
          
          # 提取各个部分
          department = extract_section(body, "部门名称")
          title = extract_section(body, "标题")
          filename = extract_section(body, "文件名")
          content = extract_content(body)
          
          # 打印提取结果（调试用）
          print(f"部门名称: {department}")
          print(f"标题: {title}")
          print(f"文件名: {filename}")
          print(f"内容长度: {len(content) if content else 0}")
          
          # 验证必要字段
          missing = []
          if not department:
              missing.append("部门名称")
          if not filename:
              missing.append("文件名")
          if not content:
              missing.append("主要内容")
              
          if missing:
              print(f"错误: 缺少必要字段: {', '.join(missing)}")
              sys.exit(1)
          
          # 输出到环境变量
          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
              f.write(f"DEPARTMENT={department}\n")
              f.write(f"FILENAME={filename}\n")
              if title:
                  f.write(f"TITLE={title}\n")
              f.write(f"CONTENT<<EOF_CONTENT\n{content}\nEOF_CONTENT\n")
          EOF
          
          # 执行提取脚本
          python extract.py

      - name: 检查Issue解析失败
        if: ${{ failure() && steps.extract-fields.outcome == 'failure' }}
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ 错误：无法从Issue内容中提取必要信息。请确保包含以下必要字段：\n\n```\n### 部门名称\n<部门名称>\n\n### 文件名\n<文件名>\n\n### 主要内容\n```markdown\n<内容>\n```\n```'
            })

      - name: 匹配部门目录
        id: find-department
        env:
          DEPARTMENT: ${{ steps.extract-fields.outputs.DEPARTMENT }}
        run: |
          # 遍历 src 子目录查找匹配的 title
          BASE_DIR="src"
          TARGET_DIR=""
          
          for dir in $(find $BASE_DIR -maxdepth 1 -type d); do
            readme="$dir/README.md"
            if [ -f "$readme" ]; then
              frontmatter=$(sed -n '/^---$/,/^---$/p' $readme | head -n -1 | tail -n +2)
              # 使用Python处理YAML前置内容，避免yq命令语法问题
              title=$(python -c "import yaml; print(yaml.safe_load('''$frontmatter''').get('title', ''))")
              
              if [ "$title" = "$DEPARTMENT" ]; then
                TARGET_DIR="${dir#*/}"  # 去除前面的 src/
                break
              fi
            fi
          done

          if [ -z "$TARGET_DIR" ]; then
            echo "未找到匹配部门目录！"
            exit 1
          fi

          echo "target_dir=$TARGET_DIR" >> $GITHUB_OUTPUT

      - name: 生成文件
        id: generate-file
        env:
          DEPARTMENT: ${{ steps.extract-fields.outputs.DEPARTMENT }}
          FILENAME: ${{ steps.extract-fields.outputs.FILENAME }}
          TITLE: ${{ steps.extract-fields.outputs.TITLE }}
          CONTENT: ${{ steps.extract-fields.outputs.CONTENT }}
          TARGET_DIR: ${{ steps.find-department.outputs.target_dir }}
        run: |
          # 清理文件名并创建路径
          CLEAN_FILENAME=$(echo "$FILENAME" | tr ' ' '-' | tr -cd '[:alnum:]-_')
          FILE_PATH="src/$TARGET_DIR/${CLEAN_FILENAME}.md"
          echo "file_path=$FILE_PATH" >> $GITHUB_OUTPUT
          
          # 写入内容
          ARTICLE_TITLE="${TITLE:-来自 $DEPARTMENT 的投稿}"
          echo "# $ARTICLE_TITLE" > $FILE_PATH
          echo -e "\n---\n" >> $FILE_PATH
          echo "$CONTENT" >> $FILE_PATH
          echo -e "\n---\n" >> $FILE_PATH
          echo "> 投稿人: @${{ github.event.issue.user.login }}" >> $FILE_PATH

      - name: 创建分支并提交更改
        id: create-branch
        env:
          FILENAME: ${{ steps.extract-fields.outputs.FILENAME }}
        run: |
          # 创建并切换到新分支
          BRANCH_NAME="content-update/$FILENAME-${{ github.run_id }}"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b $BRANCH_NAME
          git add .
          git commit -m "添加内容: $FILENAME (部门: ${{ steps.extract-fields.outputs.DEPARTMENT }})"
          git push origin $BRANCH_NAME
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "repo_url=https://github.com/${{ github.repository }}" >> $GITHUB_OUTPUT

      - name: 尝试创建Pull Request
        id: create-pr
        continue-on-error: true
        uses: peter-evans/create-pull-request@v5
        env:
          DEPARTMENT: ${{ steps.extract-fields.outputs.DEPARTMENT }}
          FILENAME: ${{ steps.extract-fields.outputs.FILENAME }}
          TITLE: ${{ steps.extract-fields.outputs.TITLE }}
          TARGET_DIR: ${{ steps.find-department.outputs.target_dir }}
        with:
          branch: ${{ steps.create-branch.outputs.branch_name }}
          base: main
          title: "内容投稿: ${{ steps.extract-fields.outputs.DEPARTMENT }} - ${{ steps.extract-fields.outputs.TITLE || steps.extract-fields.outputs.FILENAME }}"
          body: |
            由 Issue #${{ github.event.issue.number }} 自动生成
            部门目录: `src/${{ steps.find-department.outputs.target_dir }}`
          commit-message: "添加内容: ${{ steps.extract-fields.outputs.FILENAME }} (部门: ${{ steps.extract-fields.outputs.DEPARTMENT }})"
          labels: "content-submission"

      - name: PR创建失败处理
        if: steps.create-pr.outcome == 'failure'
        uses: actions/github-script@v6
        env:
          BRANCH_NAME: ${{ steps.create-branch.outputs.branch_name }}
          REPO_URL: ${{ steps.create-branch.outputs.repo_url }}
          FILE_PATH: ${{ steps.generate-file.outputs.file_path }}
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `✅ 文件已成功生成并提交到分支 \`${process.env.BRANCH_NAME}\`！

              但由于GitHub Actions权限限制，无法自动创建Pull Request。请手动完成以下步骤：

              1. 点击此链接创建PR: ${process.env.REPO_URL}/compare/main...${process.env.BRANCH_NAME}?expand=1
              2. 设置标题为: "内容投稿: ${{ steps.extract-fields.outputs.DEPARTMENT }} - ${{ steps.extract-fields.outputs.TITLE || steps.extract-fields.outputs.FILENAME }}"
              3. 审核文件 \`${process.env.FILE_PATH}\` 并提交PR

              **提示**: 如需解决此问题，可以在仓库设置中启用"Allow GitHub Actions to create and approve pull requests"选项。`
            })

      - name: 检查部门是否存在
        if: ${{ failure() && steps.find-department.outcome == 'failure' }}
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ 错误：未找到与部门名称匹配的目录，请检查部门名称是否正确'
            })
