name: Process Department Content

on:
  issues:
    types: [opened, edited]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  generate-content:
    runs-on: ubuntu-latest
    steps:
      - name: 立即回复“已收到，正在处理...”
        id: initial-comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "✅ 已收到您的投稿请求，正在处理...\n\n请稍等，我们会尽快完成解析并生成内容。"
            });

            // 记录评论 ID 以便后续更新
            core.setOutput("comment_id", response.data.id);

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 安装依赖
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.35.1/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          pip install pyyaml

      - name: 提取模板字段
        id: extract-fields
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          cat > extract.py << 'EOF'
          import os, sys, re

          def extract_section(body, section_name):
              """提取指定部分的内容"""
              marker = f"### {section_name}"
              start = body.find(marker)
              if start == -1:
                  return None
              start += len(marker)
              end = body.find("###", start)
              return body[start:end].strip() if end != -1 else body[start:].strip()

          def extract_content(body):
              """提取内容 - 从第一个```markdown到最后一个```"""
              start = body.find("```markdown")
              if start == -1:
                  return None
              start = body.find("\n", start) + 1
              end = body.rfind("```")
              return body[start:end].strip() if end != -1 and end > start else None

          body = os.environ.get("ISSUE_BODY", "")
          department = extract_section(body, "部门名称")
          title = extract_section(body, "标题")
          filename = extract_section(body, "文件名")
          content = extract_content(body)

          if not department or not filename or not content:
              print("错误: 缺少必要字段")
              sys.exit(1)

          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
              f.write(f"DEPARTMENT={department}\n")
              f.write(f"FILENAME={filename}\n")
              f.write(f"CONTENT<<EOF\n{content}\nEOF\n")
          EOF
          python extract.py

      - name: 匹配部门目录
        id: find-department
        env:
          DEPARTMENT: ${{ steps.extract-fields.outputs.DEPARTMENT }}
        run: |
          BASE_DIR="src"
          TARGET_DIR=""

          for dir in $(find $BASE_DIR -maxdepth 1 -type d); do
            readme="$dir/README.md"
            if [ -f "$readme" ]; then
              frontmatter=$(sed -n '/^---$/,/^---$/p' $readme | tail -n +2 | head -n -1)
              title=$(python -c "import yaml; print(yaml.safe_load('''$frontmatter''').get('title', ''))")
              if [ "$title" = "$DEPARTMENT" ]; then
                TARGET_DIR="${dir#*/}"
                break
              fi
            fi
          done

          if [ -z "$TARGET_DIR" ]; then
            echo "未找到匹配部门目录！"
            exit 1
          fi
          echo "target_dir=$TARGET_DIR" >> $GITHUB_OUTPUT

      - name: 生成文件
        id: generate-file
        env:
          DEPARTMENT: ${{ steps.extract-fields.outputs.DEPARTMENT }}
          FILENAME: ${{ steps.extract-fields.outputs.FILENAME }}
          CONTENT: ${{ steps.extract-fields.outputs.CONTENT }}
          TARGET_DIR: ${{ steps.find-department.outputs.target_dir }}
        run: |
          CLEAN_FILENAME=$(echo "$FILENAME" | tr ' ' '-' | tr -cd '[:alnum:]-_')
          FILE_PATH="src/$TARGET_DIR/${CLEAN_FILENAME}.md"
          echo "file_path=$FILE_PATH" >> $GITHUB_OUTPUT

          echo "---" > $FILE_PATH
          echo "title: ${FILENAME}" >> $FILE_PATH
          echo "---" >> $FILE_PATH
          echo "" >> $FILE_PATH
          echo "$CONTENT" >> $FILE_PATH

      - name: 创建分支并提交更改
        id: create-branch
        env:
          FILENAME: ${{ steps.extract-fields.outputs.FILENAME }}
          FILE_PATH: ${{ steps.generate-file.outputs.file_path }}
        run: |
          BRANCH_NAME="content-update/$(date +%Y%m%d%H%M%S)"
          git checkout -b $BRANCH_NAME
          git add "$FILE_PATH"
          git commit -m "添加内容: $FILENAME"
          git push --force origin $BRANCH_NAME
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: 创建 PR
        id: create-pr
        uses: actions/github-script@v6
        env:
          BRANCH_NAME: ${{ steps.create-branch.outputs.branch_name }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `内容投稿: ${{ steps.extract-fields.outputs.DEPARTMENT }} - ${{ steps.extract-fields.outputs.FILENAME }}`,
              body: `由 Issue #${context.issue.number} 自动生成`,
              head: process.env.BRANCH_NAME,
              base: 'main'
            });
            core.setOutput("pr_url", response.data.html_url);

      - name: 更新评论为最终状态
        if: always()
        uses: actions/github-script@v6
        env:
          COMMENT_ID: ${{ steps.initial-comment.outputs.comment_id }}
          FILE_PATH: ${{ steps.generate-file.outputs.file_path }}
          PR_URL: ${{ steps.create-pr.outputs.pr_url }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commentId = process.env.COMMENT_ID;
            let updatedBody;

            if ('${{ success() }}' === 'true') {
              updatedBody = `✅ **处理完成！**
              - 生成文件: \`${process.env.FILE_PATH}\`
              - [查看 PR](${process.env.PR_URL})\n🎉 您的内容已成功提交！`;
            } else {
              updatedBody = `⚠ **处理失败！** 可能的错误原因: 提取字段失败、Git 操作失败等。请检查 Issue 格式。`;
            }

            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: commentId,
              body: updatedBody
            });
